services:
  app:
    build: .
    container_name: organizations_app
    command: sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/app/app
      - ./alembic.ini:/app/alembic.ini
      - ./alembic:/app/alembic
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@database:5432/organization_catalog
      - API_KEY=secret_key
      - DEBUG=true
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: organization_catalog
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tests/test_data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: